services:
  sodamaricela:
    build: .
    container_name: astro-sodamaricela
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sodamaricela.rule=Host(`dev.sodamaricela.com`) || Host(`sodamaricela.com`)"
      - "traefik.http.routers.sodamaricela.entrypoints=web"
      - "traefik.http.services.sodamaricela.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
