services:
  sodamaricela:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: astro-sodamaricela
    restart: unless-stopped
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sodamaricela.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.sodamaricela.entrypoints=web"
      - "traefik.http.services.sodamaricela.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
